Fetkullovaaa 2
fetkullovaaa/stat pull request #2
Opened 2022-10-09 11:13 UTC by fetkullovaaa

2022-10-09 19:15 UTC, dmitrii-kruglov requested changes
Осталось дорешать одну задачу. Удалите, пожалуйста, ненужный файл из ветки

2022-10-09 19:15 UTC, dmitrii-kruglov commented on notebooks_Intro 3.ipynb
> +      "source": "chislo = input()\nif chislo % 10 == 7:\n    print (True)\nelse:\n    print(False)\n",
Можно было просто вывести результат операции сравнения

2022-10-09 19:15 UTC, dmitrii-kruglov commented on notebooks_Intro 4.ipynb
> +      "source": "a = float(input())\nb = float(input())\nc = float(input())\nd = b*b-4*a*c\nif d < 0:\n    print(\"решений нет\")\nelif d == 0:\n    print(\"x=\", (-b/(2*a)))\nelse:\n    print(\"x1=\
Рассмотрите ситуацию когда a будет 0

2022-10-11 08:21 UTC, dmitrii-kruglov requested changes
Разделите пожалуйста ввод и вывод на разные кодовые блоки. Иначе одно перезатирает другое

2022-10-11 08:21 UTC, dmitrii-kruglov commented on notebooks_Intro 5.ipynb
> +          "evalue": "float() argument must be a string or a real number, not 'Future'",
У вас программа работает с ошибками

2022-10-11 08:21 UTC, dmitrii-kruglov commented on notebooks_Intro 5.ipynb
> +      "source": "a = int(input())\nb = int(input())\nc = int(input())\nmaxchislo = a\nif b>maxchislo:\n    maxchislo=b\nif c>maxchislo:\n    maxchislo=c\nprint(maxchislo)",
Не вижу результатов прогона

2022-10-11 08:21 UTC, dmitrii-kruglov commented on notebooks_Intro 5.ipynb
> +      "source": "chislo = int(input())\nsumm = 0\nsr = 0\nk = 0\nfor i in range (0,chislo+1):\n    if i%5==0 or i%2!=0:\n        summ += i\n        k+=1\n    sr = summ/k\nprint(round(sr, 2))",
У этого тоже нет результатов

2022-10-13 09:20 UTC, fetkullovaaa commented on notebooks_Intro 5.ipynb
> +      "source": "a = int(input())\nb = int(input())\nc = int(input())\nmaxchislo = a\nif b>maxchislo:\n    maxchislo=b\nif c>maxchislo:\n    maxchislo=c\nprint(maxchislo)",
У меня не получается в Jupiter это сделать, в онлайн компиляторе все работало

2022-10-13 11:27 UTC, dmitrii-kruglov approved these changes
Очень жаль, что так и не увидел прогонов кода с вашими данными.
3 балла.

2022-10-13 11:28 UTC, dmitrii-kruglov commented
Удаляйте, пожалуйста, не нужные файлы, когда загружаете новый

2022-10-13 14:20 UTC, merged